[versions]
agp = "8.9.3"
desugar_jdk_libs = "2.1.5"
kotlin = "2.1.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
firebase_plugin="4.4.3"
firebase-auth="24.0.0"
webCore="5.0.1"
security-crypto="1.1.0"
bitcoinj-core="0.17"
recyclerview="1.4.0"
qrgen="2.6.0"
socket    = "2.1.0"
dagger-hilt = "2.56.2"
android-ksp = "2.1.10-1.0.29"
okhttp = "5.3.0"
gson = "2.13.2"
retrofit = "2.9.0"
fragment = "1.8.9"
rxbinding = "4.0.0"
activity = "1.12.3"
viewpager2 = "1.1.0"
timber = "5.0.1"
sdp = "1.1.0"
coroutines = "1.10.2"
coil = "2.4.0"
multidex = "2.0.1"
constraintlayout = "2.2.1"
navigation = "2.9.7"
navigation-hilt = "1.3.0"
utilcodex   = "1.31.0"
bitcoin-kmp="0.25.1"
bitcoin-jni="0.18.0"
slidetoact="0.11.0"

viewmodel="2.10.0"
flexbox="3.0.0"
coroutines-test="1.10.1"
mockk="1.13.5"
hilt-testing="2.56.2"
play-credentials = "1.5.0"
play-identity = "1.2.0"
google-auth = "1.37.1"
google-auth2 = "21.5.0"
google-api-client = "2.8.0"
google-api-service = "v3-rev20220815-2.0.0"
google-coroutines="1.10.2"



# Compose Versions
compose-bom = "2026.01.01"
activity-compose = "1.12.3"
lifecycle-runtime-compose = "2.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

#///////////////// Compose ////////////////////////#
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-hilt = { group = "androidx.hilt", name = "hilt-navigation-compose" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
#//////////////////////////////////////////////////#

#///////////////// Core ////////////////////////#


web3-core={group="org.web3j",name="core",version.ref="webCore"}
web3-crypto={group="org.web3j",name="crypto",version.ref="webCore"}
web3-utils={group="org.web3j",name="utils",version.ref="webCore"}
bitcoinj={group="org.bitcoinj",name="bitcoinj-core",version.ref="bitcoinj-core"}
bitcoin-kmp={group="fr.acinq.bitcoin",name="bitcoin-kmp",version.ref="bitcoin-kmp"}
bitcoin-jni={group="fr.acinq.secp256k1",name="secp256k1-kmp-jni-android",version.ref="bitcoin-jni"}
security-crypto={group="androidx.security",name="security-crypto",version.ref="security-crypto"}

#//////////////////////////////////////////////////#
dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger-hilt" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "navigation-hilt" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
scalars-converter = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
framgnet  ={module="androidx.fragment:fragment-ktx",version.ref="fragment"}
viewModel  ={module="androidx.lifecycle:lifecycle-viewmodel-ktx",version.ref="viewmodel"}
recyclerview  ={module="androidx.recyclerview:recyclerview",version.ref="recyclerview"}
qrgen  ={module="com.github.kenglxn.qrgen:android",version.ref="qrgen"}


viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose-base", version.ref = "coil" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
sdp = { module = "com.intuit.sdp:sdp-android", version.ref = "sdp" }
ssp = { module = "com.intuit.ssp:ssp-android", version.ref = "sdp" }
navFragment = { module="androidx.navigation:navigation-fragment-ktx",version.ref="navigation" }
navUi  = { module="androidx.navigation:navigation-ui-ktx",version.ref="navigation" }
navUi-hitl  = { module="androidx.hilt:hilt-navigation-fragment",version.ref="navigation-hilt" }
utilcodex  = { module = "com.blankj:utilcodex", version.ref = "utilcodex" }
rxbinding  = { module = "com.jakewharton.rxbinding4:rxbinding", version.ref = "rxbinding" }
slidetoact  = { module = "com.ncorti:slidetoact", version.ref = "slidetoact" }
socket     = { module = "io.socket:socket.io-client",version.ref="socket"}

#///////////////////DATA///////////////#

google-credentials = { module = "androidx.credentials:credentials", version.ref = "play-credentials" }
google-credentials-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "play-credentials" }
google-identity = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "play-identity" }
google-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "google-coroutines" }

google-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "google-auth2" }
google-auth2 = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "google-auth" }
google-api-client = { module = "com.google.api-client:google-api-client-android", version.ref = "google-api-client" }
google-api-services-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "google-api-service" }









#///////////////////TEST///////////////#
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
coroutines-test={ group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
mockk={ group = "io.mockk", name = "mockk", version.ref = "mockk" }
hilt-test={ group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt-testing" }




#///////////////////////////////////////#

[bundles]
coil = ["coil", "coil-svg","coil-compose"]
google-auth=["google-credentials","google-coroutines","google-credentials-auth","google-api-client","google-auth","google-auth2","google-api-services-drive","google-identity"]
web3=["web3-core","web3-crypto","web3-utils"]
coroutines = ["coroutines", "coroutines-android"]
okhttp = ["okhttp", "okhttp-logging"]
sdp = ["sdp", "ssp"]
gson = ["gson", "gson-converter","scalars-converter"]
navigation=["navFragment","navUi","navUi-hitl"]


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-navsafeArgs  = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
android-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
android-ksp = { id = "com.google.devtools.ksp", version.ref = "android-ksp" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
